export enum BusinessTypeEnum {
  BT_POWER_CUT = 'power-cut',
  BT_POWER_TASK = 'power-task',
  BT_MAINT_ORDER = 'maintenance-order',
  BT_MAINT_PLAN = 'maintenance-plan',
  BT_PROD_CHECK = 'prod-check',
  NBT_PLC_ALERT = 'plc-alert',
  NBT_DEVICE_LUBRICATE = 'device-lubricate',
  NBT_LUBRICATION_ORDER_TASK = 'device-lubricate',
  NBT_DEVICE_PROBLEM = 'device-problem',
  NBT_QUALITY_INSPECTION = 'quality-inspection',
  NBT_ENERGY_COST_OVERLOAD = 'energy-cost-overload',
  NBT_REPAIR_ORDER = 'repair-order',
  NBT_PRODUCTION_REPORT = 'production-report',
  NBT_PRODUCTION_YIELD_ANALYSIS = 'production-yield-analysis',
  NBT_SAFE_REVIEW_TASK = 'safe-review-task',
  NBT_SPARE_PART_STOCK_WARNING = 'spare-part-stock-warning',
  NBT_MAINTENANCE_ORDER_TASK = 'maintenance-order',
}
